# Data loader

I wrote some helper functions to make loading data easier for experimentation. The code is located in `Notebook/utils/data_loader.py`. Below is examples of how to use it.

In [1]:
from utils.data_loader import Dataset

Everything is housed inside a `Dataset`. It only requires a name (used for saving and loading).

In [2]:
train_ds = Dataset(name='my_training_dataset')

Initially it does nothing. You can always see what data it has actually loaded by accessing the `.data` attribute, which is a Pandas DataFrame.

In [3]:
train_ds.data == None

True

## Games

Load games using the `load_games` method. Optionally you can specify start and end dates. By default it gets all data from 2000 to 2015 inclusive.

In [4]:
train_ds.load_games(start_date='2000-01-01', end_date='2003-01-01')

,date,Y,M,D,home_team,away_team,home_win,home_pitcher,away_pitcher,home_elo,...,avg_diff,obp_diff,slg_diff,avg_pct_diff,obp_pct_diff,slg_pct_diff,home_rest,away_rest,away_team_season_game_num,home_team_season_game_num
0,2001-04-01,2001,4.0,1.0,TOR,TEX,1.0,loaizes01,helliri01,1499.562988,...,-0.008060,-0.010103,0.023271,-2.947374,-2.977845,4.989568,5.0,5.0,0,0
1,2001-04-02,2001,4.0,2.0,SEA,OAK,1.0,garcifr03,hudsoti01,1519.463989,...,-0.000864,0.001190,-0.016229,-0.323318,0.331871,-3.705210,5.0,5.0,0,0
2,2001-04-02,2001,4.0,2.0,NYA,KCA,1.0,clemero02,suppaje01,1529.510986,...,-0.010188,0.006929,0.024787,-3.703559,1.970596,5.554343,5.0,5.0,0,0
3,2001-04-02,2001,4.0,2.0,CIN,ATL,0.0,harnipe01,burkejo03,1527.274048,...,0.003972,-0.001729,0.020216,1.459194,-0.506960,4.555242,5.0,5.0,0,0
4,2001-04-02,2001,4.0,2.0,CHN,WAS,0.0,liebejo01,vazquja01,1462.510010,...,-0.010158,0.009335,-0.018992,-3.996340,2.803560,-4.646432,5.0,5.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4850,2002-09-29,2002,9.0,29.0,TEX,OAK,0.0,benoijo01,zitoba01,1498.168945,...,-0.004118,-0.015355,-0.006046,-1.562305,-4.366582,-1.402798,1.0,1.0,80,80
4851,2002-09-29,2002,9.0,29.0,SLN,MIL,1.0,benesan01,frankwa01,1564.499023,...,0.043451,0.055172,0.090154,17.782738,16.750874,22.641031,1.0,1.0,80,80
4852,2002-09-29,2002,9.0,29.0,LAN,SDN,0.0,alvarvi01,perezol01,1538.897949,...,0.079375,0.086138,0.092961,29.143755,25.025467,24.589701,1.0,1.0,80,80
4853,2002-09-29,2002,9.0,29.0,ARI,COL,1.0,pattejo02,starkde01,1556.958008,...,0.006467,0.046106,0.085538,2.213280,11.996187,16.898954,1.0,1.0,80,80
4854,2002-09-29,2002,9.0,29.0,ANA,SEA,1.0,seleaa01,valdeis01,1572.269043,...,-0.005766,-0.003741,0.011036,-2.177349,-1.169065,2.710832,1.0,1.0,80,80

This returns all games in the requested date range (data comes from `data/mlb_games_df.csv`). It returns the data, but it's also always saved at the `.data` attribute.

In [5]:
# The same as what was printed out above
train_ds.data.head()

,date,Y,M,D,home_team,away_team,home_win,home_pitcher,away_pitcher,home_elo,...,avg_diff,obp_diff,slg_diff,avg_pct_diff,obp_pct_diff,slg_pct_diff,home_rest,away_rest,away_team_season_game_num,home_team_season_game_num
0,2001-04-01,2001,4.0,1.0,TOR,TEX,1.0,loaizes01,helliri01,1499.562988,...,-0.008060,-0.010103,0.023271,-2.947374,-2.977845,4.989568,5.0,5.0,0,0
1,2001-04-02,2001,4.0,2.0,SEA,OAK,1.0,garcifr03,hudsoti01,1519.463989,...,-0.000864,0.001190,-0.016229,-0.323318,0.331871,-3.705210,5.0,5.0,0,0
2,2001-04-02,2001,4.0,2.0,NYA,KCA,1.0,clemero02,suppaje01,1529.510986,...,-0.010188,0.006929,0.024787,-3.703559,1.970596,5.554343,5.0,5.0,0,0
3,2001-04-02,2001,4.0,2.0,CIN,ATL,0.0,harnipe01,burkejo03,1527.274048,...,0.003972,-0.001729,0.020216,1.459194,-0.506960,4.555242,5.0,5.0,0,0
4,2001-04-02,2001,4.0,2.0,CHN,WAS,0.0,liebejo01,vazquja01,1462.510010,...,-0.010158,0.009335,-0.018992,-3.996340,2.803560,-4.646432,5.0,5.0,0,0

## Team stats

You can add team stats (from `data/team_stats.csv`) from previous years. To do so, use the `.add_team_stats()` method. By default it uses the previous years data, but you can add different/more years by specifying `year_offset` (default of 1). So, for example, `year_offset=2` would get team stats from two years prior. Columns are named `home/away_{col_name}_offset{year_offset}years`. So for example, `home_Avg_Attendance_offset1` for average attendance for the home team last year.

By default, **no columns are actually loaded from the team stats**, so you need to specify them using `cols=[...]`. Again, check out the `team_stats.csv` file to see what columns are available.

In [6]:
train_ds.add_team_stats(cols=['Avg_Attendance', 'W-L-pct'])

,date,Y,M,D,home_team,away_team,home_win,home_pitcher,away_pitcher,home_elo,...,obp_pct_diff,slg_pct_diff,home_rest,away_rest,away_team_season_game_num,home_team_season_game_num,home_Avg_Attendance_offset1year,home_W-L-pct_offset1year,away_Avg_Attendance_offset1year,away_W-L-pct_offset1year
0,2001-04-01,2001,4.0,1.0,TOR,TEX,1.0,loaizes01,helliri01,1499.562988,...,-2.977845,4.989568,5.0,5.0,0,0,24861.419753,0.512346,32341.993789,0.438272
20,2001-04-24,2001,4.0,24.0,TOR,TEX,1.0,hamiljo02,davisdo02,1513.202026,...,-15.287162,-21.483376,2.0,2.0,10,10,24861.419753,0.512346,32341.993789,0.438272
40,2001-04-25,2001,4.0,25.0,TOR,TEX,1.0,carpech01,rogerke01,1514.573975,...,-19.726679,-25.543036,1.0,1.0,11,11,24861.419753,0.512346,32341.993789,0.438272
60,2001-08-17,2001,8.0,17.0,TOR,TEX,1.0,loaizes01,oliveda02,1486.626953,...,10.999306,20.949846,1.0,1.0,61,63,24861.419753,0.512346,32341.993789,0.438272
80,2001-08-18,2001,8.0,18.0,TOR,TEX,0.0,hallaro01,bellro01,1489.930054,...,4.948137,15.053859,1.0,1.0,62,64,24861.419753,0.512346,32341.993789,0.438272
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92951,2002-08-03,2002,8.0,3.0,SDN,CIN,0.0,tomkobr01,hayneji01,1474.746948,...,4.474744,15.819613,1.0,1.0,54,55,30563.919255,0.487654,28449.643750,0.407407
92971,2002-08-04,2002,8.0,4.0,SDN,CIN,0.0,jonesbo03,dempsry01,1473.321045,...,-2.340771,-0.447244,1.0,1.0,55,56,30563.919255,0.487654,28449.643750,0.407407
92991,2002-06-07,2002,6.0,7.0,ANA,CIN,1.0,seleaa01,reitsch01,1531.149048,...,12.287816,29.475273,1.0,1.0,29,31,27714.104938,0.462963,28449.643750,0.407407
93011,2002-06-08,2002,6.0,8.0,ANA,CIN,0.0,ortizra02,desseel01,1532.250977,...,11.639690,31.446281,1.0,1.0,30,32,27714.104938,0.462963,28449.643750,0.407407
93031,2002-06-09,2002,6.0,9.0,ANA,CIN,1.0,schoesc01,hamiljo02,1530.613037,...,-0.855070,26.631958,1.0,1.0,31,33,27714.104938,0.462963,28449.643750,0.407407

## Team pitching

Similarly, you can add team pitching stats (at a team-level, _not_ a pitcher level) using `.add_team_pitching_stats()`. The parameters are the same as `.add_team_stats()`. Data comes from `data/team_pitching_stats.csv`.

In [7]:
train_ds.add_team_pitching_stats(cols=['WHIP', 'ERA'])

,date,Y,M,D,home_team,away_team,home_win,home_pitcher,away_pitcher,home_elo,...,away_team_season_game_num,home_team_season_game_num,home_Avg_Attendance_offset1year,home_W-L-pct_offset1year,away_Avg_Attendance_offset1year,away_W-L-pct_offset1year,home_WHIP_offset1year,home_ERA_offset1year,away_WHIP_offset1year,away_ERA_offset1year
0,2001-04-01,2001,4.0,1.0,TOR,TEX,1.0,loaizes01,helliri01,1499.562988,...,0,0,24861.419753,0.512346,32341.993789,0.438272,1.513465,5.17,1.640308,5.52
20,2001-04-24,2001,4.0,24.0,TOR,TEX,1.0,hamiljo02,davisdo02,1513.202026,...,10,10,24861.419753,0.512346,32341.993789,0.438272,1.513465,5.17,1.640308,5.52
40,2001-04-25,2001,4.0,25.0,TOR,TEX,1.0,carpech01,rogerke01,1514.573975,...,11,11,24861.419753,0.512346,32341.993789,0.438272,1.513465,5.17,1.640308,5.52
60,2001-08-17,2001,8.0,17.0,TOR,TEX,1.0,loaizes01,oliveda02,1486.626953,...,61,63,24861.419753,0.512346,32341.993789,0.438272,1.513465,5.17,1.640308,5.52
80,2001-08-18,2001,8.0,18.0,TOR,TEX,0.0,hallaro01,bellro01,1489.930054,...,62,64,24861.419753,0.512346,32341.993789,0.438272,1.513465,5.17,1.640308,5.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90520,2001-05-08,2001,5.0,8.0,ARI,CIN,1.0,johnsra05,reitsch01,1518.121948,...,16,17,33104.598765,0.524691,34630.858025,0.524691,1.344928,4.36,1.445642,4.33
90540,2001-05-09,2001,5.0,9.0,ARI,CIN,1.0,ellisro02,desseel01,1519.371948,...,17,18,33104.598765,0.524691,34630.858025,0.524691,1.344928,4.36,1.445642,4.33
90561,2002-08-20,2002,8.0,20.0,ARI,CIN,1.0,johnsra05,dempsry01,1579.623047,...,59,59,32990.739130,0.567901,28449.643750,0.407407,1.242462,3.88,1.447095,4.78
90581,2002-08-21,2002,8.0,21.0,ARI,CIN,1.0,schilcu01,moehlbr01,1580.656006,...,60,60,32990.739130,0.567901,28449.643750,0.407407,1.242462,3.88,1.447095,4.78
90601,2002-08-22,2002,8.0,22.0,ARI,CIN,1.0,batismi01,reitsch01,1582.944946,...,61,61,32990.739130,0.567901,28449.643750,0.407407,1.242462,3.88,1.447095,4.78

## Pitcher stats

Finally, you can add stats for an individual pitcher (from `data/pitchers_games.csv`). Rather than a year offset, this uses `game_offset`, and only considers games from the same season (so for the first game of the season any "previous" stats will be `None`). By default it uses the previous games stats. Note that these are games where that pitcher started, so it's possible to have stats come from several games back, if that were the most recent game in which the pitcher started (I can change this is you'd like it to ignore who the starting pitcher is).

**Note:** This function is fairly slow, especially for a big block of seasons. It's grabbing _all_ past games for this pitcher, filtering, and manipulating. So if you've loaded all the data you want, consider using the `.save()` method below so you don't have to reload it over and over.

In [ ]:
train_ds.add_pitcher_stats(cols=['WHIP', 'ERA', 'IP'])

/Users/psavala/.virtualenvs/baseball/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3343: DtypeWarning: Columns (16) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

## Saving and loading

Finally, you can save and load your data easily. By default files are saved to `data/saved_datasets/{your_dataset_name}.csv`.

In [19]:
train_ds.save()

If you want to load some data that you previous saved, create a new blank dataset with the same name as your saved data (so for example, to load the dataset we just saved we would create a new dataset with the same `name='my_training_dataset'`). Then run `.load()`.

In [20]:
new_train_ds = Dataset(name='my_training_dataset')
new_train_ds.load()

In [21]:
new_train_ds.data.head()

,away_team_season_game_num,home_team_season_game_num,date,Y,M,D,home_team,away_team,home_win,home_pitcher,...,team_home_WHIP_offset1,team_home_ERA_offset1,team_away_WHIP_offset1,team_away_ERA_offset1,pitcher_home_WHIP_offset1,pitcher_home_ERA_offset1,pitcher_home_IP_offset1,pitcher_away_WHIP_offset1,pitcher_away_ERA_offset1,pitcher_away_IP_offset1
0,13,13,2001-04-28,2001,4.0,28.0,CHA,SEA,0.0,biddlro01,...,1.464037,4.67,1.440466,4.53,2.549020,3.86,5.1,NaN,NaN,NaN
1,18,19,2001-05-11,2001,5.0,11.0,TOR,SEA,0.0,hamiljo02,...,1.513465,5.17,1.440466,4.53,1.285714,4.99,7.0,1.568628,4.70,5.1
2,21,22,2001-05-22,2001,5.0,22.0,MIN,SEA,1.0,radkebr01,...,1.501187,5.16,1.440466,4.53,2.195122,3.39,4.1,4.545454,6.66,2.2
3,26,26,2001-05-28,2001,5.0,28.0,KCA,SEA,0.0,durbich01,...,1.582934,5.48,1.440466,4.53,3.333333,5.20,3.0,1.000000,5.67,9.0
4,28,35,2001-06-14,2001,6.0,14.0,COL,SEA,0.0,astacpe01,...,1.507692,5.29,1.440466,4.53,2.000000,5.28,6.0,1.142857,4.25,7.0

In [23]:
new_train_ds.data.shape == train_ds.data.shape

True